// Permission is hereby granted, free of charge, to any person obtaining
// a copy of this software and associated documentation files (the
// "Software"), to deal in the Software without restriction, including
// without limitation the rights to use, copy, modify, merge, publish,
// distribute, sublicense, and/or sell copies of the Software, and to
// permit persons to whom the Software is furnished to do so, subject to
// the following conditions:
//
// The above copyright notice and this permission notice shall be
// included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
// LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
// OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
// WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
// Copyright (c) 2005 Novell, Inc.
//
// Authors:
//	Jordi Mas i Hernandez, jordi@ximian.com
//
//
// A single ComboBox with many items and easy to change between modes
//

using System;
using System.Drawing;
using System.Windows.Forms;

namespace MyFormProject 
{
	class MainForm : Form
	{
		private Label label;
		private ComboBox comboBox;
		private Button buttonSimple;
		private Button buttonDropDown;
		private Button buttonDropDownList;

		public MainForm()
		{
			InitializeComponent();
		}
	
		void InitializeComponent() 
		{
			comboBox = new ComboBox ();			
			this.SuspendLayout();
			// 
			// comboBox
			// 
			this.comboBox.Items.AddRange (new object[]
			{
				"Abella de la Conca             ",
				"Abrera                         ",
				"Agramunt                       ",
				"Aguilar de Segarra             ",
				"Agullana                       ",
				"Aiguafreda                     ",
				"Aiguamúrcia                    ",
				"Aiguaviva                      ",
				"Aitona                         ",
				"Alamús                         ",
				"Albagés                        ",
				"Albanyà                        ",
				"Albatàrrec                     ",
				"Albesa                         ",
				"Albi                           ",
				"Albinyana                      ",
				"Albiol                         ",
				"Albons                         ",
				"Alcanar                        ",
				"Alcanó                         ",
				"Alcarràs                       ",
				"Alcoletge                      ",
				"Alcover                        ",
				"Aldea                          ",
				"Aldover                        ",
				"Aleixar                        ",
				"Alella                         ",
				"Alfara de Carles               ",
				"Alfarràs                       ",
				"Alfés                          ",
				"Alforja                        ",
				"Algerri                        ",
				"Alguaire                       ",
				"Alins                          ",
				"Alió                           ",
				"Almacelles                     ",
				"Almatret                       ",
				"Almenar                        ",
				"Almoster                       ",
				"Alp                            ",
				"Alpens                         ",
				"Alpicat                        ",
				"Alt Àneu                       ",
				"Altafulla                      ",
				"Alàs i Cerc                    ",
				"Alòs de Balaguer               ",
				"Amer                           ",
				"Ametlla de Mar                 ",
				"Ametlla del Vallès             ",
				"Ampolla                        ",
				"Amposta                        ",
				"Anglesola                      ",
				"Anglès                         ",
				"Arbeca                         ",
				"Arbolí                         ",
				"Arboç                          ",
				"Arbúcies                       ",
				"Arenys de Mar                  ",
				"Arenys de Munt                 ",
				"Argelaguer                     ",
				"Argentera                      ",
				"Argentona                      ",
				"Argençola                      ",
				"Armentera                      ",
				"Arnes                          ",
				"Arres                          ",
				"Arsèguel                       ",
				"Artesa de Lleida               ",
				"Artesa de Segre                ",
				"Artés                          ",
				"Ascó                           ",
				"Aspa                           ",
				"Avellanes i Santa Linya        ",
				"Avinyonet de Puigventós        ",
				"Avinyonet del Penedès          ",
				"Avinyó                         ",
				"Avià                           ",
				"Badalona                       ",
				"Badia del Vallès               ",
				"Bagà                           ",
				"Baix Pallars                   ",
				"Balaguer                       ",
				"Balenyà                        ",
				"Balsareny                      ",
				"Banyeres del Penedès           ",
				"Banyoles                       ",
				"Barbens                        ",
				"Barberà de la Conca            ",
				"Barberà del Vallès             ",
				"Barcelona                      ",
				"Baronia de Rialb               ",
				"Bàscara                        ",
				"Bassella                       ",
				"Batea                          ",
				"Bausen                         ",
				"Begues                         ",
				"Begur                          ",
				"Belianes                       ",
				"Bell-lloc d'Urgell             ",
				"Bellaguarda                    ",
				"Bellcaire d'Empordà            ",
				"Bellcaire d'Urgell             ",
				"Bellmunt d'Urgell              ",
				"Bellmunt del Priorat           ",
				"Bellprat                       ",
				"Bellpuig                       ",
				"Bellvei                        ",
				"Bellver de Cerdanya            ",
				"Bellvís                        ",
				"Benavent de Segrià             ",
				"Benifallet                     ",
				"Benissanet                     ",
				"Berga                          ",
				"Besalú                         ",
				"Bescanó                        ",
				"Beuda                          ",
				"Bigues i Riells                ",
				"Biosca                         ",
				"Bisbal d'Empordà               ",
				"Bisbal de Falset               ",
				"Bisbal del Penedès             ",
				"Biure                          ",
				"Blancafort                     ",
				"Blanes                         ",
				"Boadella d'Empordà             ",
				"Bolvir                         ",
				"Bonastre                       ",
				"Bordils                        ",
				"Borges Blanques                ",
				"Borges del Camp                ",
				"Borrassà                       ",
				"Borredà                        ",
				"Bossòst                        ",
				"Bot                            ",
				"Botarell                       ",
				"Bovera                         ",
				"Breda                          ",
				"Bruc                           ",
				"Brull                          ",
				"Brunyola                       ",
				"Bràfim                         ",
				"Bàscara                        ",
				"Cabacés                        ",
				"Cabanabona                     ",
				"Cabanelles                     ",
				"Cabanes                        ",
				"Cabanyes                       ",
				"Cabó                           ",
				"Cabra del Camp                 ",
				"Cabrera d'Igualada             ",
				"Cabrera de Mar                 ",
				"Cabrils                        ",
				"Cadaqués                       ",
				"Calaf                          ",
				"Calafell                       ",
				"Calders                        ",
				"Caldes d'Estrac                ",
				"Caldes de Malavella            ",
				"Caldes de Montbui              ",
				"Calella                        ",
				"Calldetenes                    ",
				"Callús                         ",
				"Calonge                        ",
				"Calonge de Segarra             ",
				"Camarasa                       ",
				"Camarles                       ",
				"Cambrils                       ",
				"Camós                          ",
				"Campdevànol                    ",
				"Campelles                      ",
				"Campins                        ",
				"Campllong                      ",
				"Camprodon                      ",
				"Canejan                        ",
				"Canet d'Adri                   ",
				"Canet de Mar                   ",
				"Canovelles                     ",
				"Cantallops                     ",
				"Canyelles                      ",
				"Capafonts                      ",
				"Capellades                     ",
				"Capmany                        ",
				"Capolat                        ",
				"Capçanes                       ",
				"Cardedeu                       ",
				"Cardona                        ",
				"Carme                          ",
				"Caseres                        ",
				"Casserres                      ",
				"Cassà de la Selva              ",
				"Castell de Mur                 ",
				"Castell de l'Areny             ",
				"Castell-Platja d'Aro           ",
				"Castellar de la Ribera         ",
				"Castellar de n'Hug             ",
				"Castellar del Riu              ",
				"Castellar del Vallès           ",
				"Castellbell i el Vilar         ",
				"Castellbisbal                  ",
				"Castellcir                     ",
				"Castelldans                    ",
				"Castelldefels                  ",
				"Castellet i la Gornal          ",
				"Castellfollit de Riubregós     ",
				"Castellfollit de la Roca       ",
				"Castellfollit del Boix         ",
				"Castellgalí                    ",
				"Castellnou de Bages            ",
				"Castellnou de Seana            ",
				"Castellolí                     ",
				"Castelló d'Empúries            ",
				"Castelló de Farfanya           ",
				"Castellserà                    ",
				"Castellterçol                  ",
				"Castellvell del Camp           ",
				"Castellví de Rosanes           ",
				"Castellví de la Marca          ",
				"Catllar                        ",
				"Cava                           ",
				"Cellera de Ter                 ",
				"Celrà                          ",
				"Centelles                      ",
				"Cercs                          ",
				"Cerdanyola del Vallès          ",
				"Cervelló                       ",
				"Cervera                        ",
				"Cervià de Ter                  ",
				"Cervià de les Garrigues        ",
				"Cistella                       ",
				"Ciutadilla                     ",
				"Clariana de Cardener           ",
				"Cogul                          ",
				"Colera                         ",
				"Coll de Nargó                  ",
				"Collbató                       ",
				"Colldejou                      ",
				"Collsuspina                    ",
				"Colomers                       ",
				"Coma i la Pedra                ",
				"Conca de Dalt			",
				"Conesa                         ",
				"Constantí                      ",
				"Copons                         ",
				"Corbera d'Ebre                 ",
				"Corbera de Llobregat           ",
				"Corbins                        ",
				"Cornellà de Llobregat          ",
				"Cornellà del Terri             ",
				"Cornudella de Montsant         ",
				"Corçà                          ",
				"Creixell                       ",
				"Crespià                        ",
				"Cruïlles,Monells i Sant Sadur. ",
				"Cubelles                       ",
				"Cubells                        ",
				"Cunit                          ",
				"Cànoves i Samalús              ",
				"Darnius                        ",
				"Das                            ",
				"Deltebre                       ",
				"Dosrius                        ",
				"Duesaigües                     ",
				"Es Bòrdes                      ",
				"Escala                         ",
				"Esparreguera                   ",
				"Espinelves                     ",
				"Espluga Calba                  ",
				"Espluga de Francolí            ",
				"Esplugues de Llobregat         ",
				"Espolla                        ",
				"Esponellà                      ",
				"Espot                          ",
				"Espunyola                      ",
				"Estamariu                      ",
				"Estany                         ",
				"Estaràs                        ",
				"Esterri d'Àneu                 ",
				"Esterri de Cardós              ",
				"Falset                         ",
				"Far d'Empordà                  ",
				"Farrera                        ",
				"Fatarella                      ",
				"Febró                          ",
				"Figaró-Montmany                ",
				"Figuera                        ",
				"Figueres                       ",
				"Figuerola del Camp             ",
				"Fígols                         ",
				"Fígols i Alinyà                ",
				"Flaçà                          ",
				"Flix                           ",
				"Floresta                       ",
				"Fogars de Montclús             ",
				"Fogars de la Selva             ",
				"Foixà                          ",
				"Folgueroles                    ",
				"Fondarella                     ",
				"Fonollosa                      ",
				"Font-rubí                      ",
				"Fontanals de Cerdanya          ",
				"Fontanilles                    ",
				"Fontcoberta                    ",
				"Foradada                       ",
				"Forallac                       ",
				"Fornells de la Selva           ",
				"Fortià                         ",
				"Forès                          ",
				"Franqueses del Vallès          ",
				"Freginals                      ",
				"Fuliola                        ",
				"Fulleda                        ",
				"Gaià                           ",
				"Galera                         ",
				"Gallifa                        ",
				"Gandesa                        ",
				"Garcia                         ",
				"Garidells                      ",
				"Garriga                        ",
				"Garrigoles                     ",
				"Garriguella                    ",
				"Garrigàs                       ",
				"Gavet de la Conca              ",
				"Gavà                           ",
				"Gelida                         ",
				"Ger                            ",
				"Gimenells i el Pla de la Font  ",
				"Ginestar                       ",
				"Girona                         ",
				"Gironella                      ",
				"Gisclareny                     ",
				"Godall                         ",
				"Golmés                         ",
				"Gombrèn                        ",
				"Gósol                          ",
				"Granada                        ",
				"Granadella                     ",
				"Granera                        ",
				"Granja d'Escarp                ",
				"Granollers                     ",
				"Granyanella                    ",
				"Granyena de Segarra            ",
				"Granyena de les Garrigues      ",
				"Gratallops                     ",
				"Gualba                         ",
				"Gualta                         ",
				"Guardiola de Berguedà          ",
				"Guiamets                       ",
				"Guils de Cerdanya              ",
				"Guimerà                        ",
				"Guingueta d'Àneu               ",
				"Guissona                       ",
				"Guixers                        ",
				"Gurb                           ",
				"Horta de Sant Joan             ",
				"Hospitalet de Llobregat        ",
				"Hostalets de Pierola           ",
				"Hostalric                      ",
				"Igualada                       ",
				"Isona i Conca Dellà            ",
				"Isòvol                         ",
				"Ivars d'Urgell                 ",
				"Ivars de Noguera               ",
				"Ivorra                         ",
				"Jafre                          ",
				"Jonquera                       ",
				"Jorba                          ",
				"Josa i Tuixén                  ",
				"Juià                           ",
				"Juncosa                        ",
				"Juneda                         ",
				"Les                            ",
				"Linyola                        ",
				"Llacuna                        ",
				"Lladorre                       ",
				"Lladó                          ",
				"Lladurs                        ",
				"Llagosta                       ",
				"Llagostera                     ",
				"Llambilles                     ",
				"Llanars                        ",
				"Llançà                         ",
				"Llardecans                     ",
				"Llavorsí                       ",
				"Lleida                         ",
				"Llers                          ",
				"Lles                           ",
				"Llimiana                       ",
				"Llinars del Vallès             ",
				"Lliçà d'Amunt                  ",
				"Lliçà de Vall                  ",
				"Llívia                         ",
				"Lloar                          ",
				"Llobera                        ",
				"Llorac                         ",
				"Llorenç del Penedès            ",
				"Lloret de Mar                  ",
				"Llosses                        ",
				"Lluçà                          ",
				"Madremanya                     ",
				"Maials                         ",
				"Maià de Montcal                ",
				"Maldà                          ",
				"Malgrat de Mar                 ",
				"Malla                          ",
				"Manlleu                        ",
				"Manresa                        ",
				"Margalef                       ",
				"Marganell                      ",
				"Martorell                      ",
				"Martorelles                    ",
				"Marçà                          ",
				"Mas de Barberans               ",
				"Masarac                        ",
				"Masdenverge                    ",
				"Masies de Roda                 ",
				"Masies de Voltregà             ",
				"Masllorenç                     ",
				"Masnou                         ",
				"Masó                           ",
				"Maspujols                      ",
				"Masquefa                       ",
				"Masroig                        ",
				"Massalcoreig                   ",
				"Massanes                       ",
				"Massoteres                     ",
				"Matadepera                     ",
				"Mataró                         ",
				"Maçanet de Cabrenys            ",
				"Maçanet de la Selva            ",
				"Mediona                        ",
				"Menàrguens                     ",
				"Meranges                       ",
				"Mieres                         ",
				"Milà                           ",
				"Miralcamp                      ",
				"Miravet                        ",
				"Moià                           ",
				"Molar                          ",
				"Molins de Rei                  ",
				"Mollerussa                     ",
				"Mollet de Peralada             ",
				"Mollet del Vallès              ",
				"Molló                          ",
				"Molsosa                        ",
				"Monistrol de Calders           ",
				"Monistrol de Montserrat        ",
				"Mont-ral                       ",
				"Mont-ras                       ",
				"Mont-roig del Camp             ",
				"Montagut                       ",
				"Montblanc                      ",
				"Montbrió del Camp              ",
				"Montcada i Reixac              ",
				"Montclar                       ",
				"Montellà i Martinet            ",
				"Montesquiu                     ",
				"Montferrer i Castellbó         ",
				"Montferri                      ",
				"Montgai                        ",
				"Montgat                        ",
				"Montmajor                      ",
				"Montmaneu                      ",
				"Montmell                       ",
				"Montmeló                       ",
				"Montoliu de Lleida             ",
				"Montoliu de Segarra            ",
				"Montornès de Segarra           ",
				"Montornès del Vallès           ",
				"Montseny                       ",
				"Morell                         ",
				"Morera de Montsant             ",
				"Móra d'Ebre                    ",
				"Móra la Nova                   ",
				"Muntanyola                     ",
				"Mura                           ",
				"Nalec                          ",
				"Naut Aran                      ",
				"Navarcles                      ",
				"Navata                         ",
				"Navàs                          ",
				"Navès                          ",
				"Nou de Berguedà                ",
				"Nou de Gaià                    ",
				"Nulles                         ",
				"Odèn                           ",
				"Ogassa                         ",
				"Olesa de Bonesvalls            ",
				"Olesa de Montserrat            ",
				"Oliana                         ",
				"Oliola                         ",
				"Olius                          ",
				"Olivella                       ",
				"Olost                          ",
				"Olot                           ",
				"Oluges                         ",
				"Olvan                          ",
				"Olèrdola                       ",
				"Omellons                       ",
				"Omells de na Gaia              ",
				"Ordis                          ",
				"Organyà                        ",
				"Oristà                         ",
				"Orís                           ",
				"Orpí                           ",
				"Os de Balaguer                 ",
				"Osor                           ",
				"Ossó de Sió                    ",
				"Pacs del Penedès               ",
				"Palafolls                      ",
				"Palafrugell                    ",
				"Palamós                        ",
				"Palau d'Anglesola              ",
				"Palau de Plegamans             ",
				"Palau de Santa Eulàlia         ",
				"Palau-sator                    ",
				"Palau-saverdera                ",
				"Pallaresos                     ",
				"Pallejà                        ",
				"Palma d'Ebre                   ",
				"Palma de Cervelló              ",
				"Palol de Revardit              ",
				"Pals                           ",
				"Papiol                         ",
				"Pardines                       ",
				"Parets del Vallès              ",
				"Parlavà                        ",
				"Passanant                      ",
				"Pau                            ",
				"Paüls                          ",
				"Pedret i Marzà                 ",
				"Penelles                       ",
				"Pera                           ",
				"Perafita                       ",
				"Perafort                       ",
				"Peralada                       ",
				"Peramola                       ",
				"Perelló                        ",
				"Piera                          ",
				"Piles                          ",
				"Pineda de Mar                  ",
				"Pinell de Brai                 ",
				"Pinell de Solsonès             ",
				"Pinós                          ",
				"Pira                           ",
				"Pla de Santa Maria             ",
				"Pla del Penedès                ",
				"Planes d'Hostoles              ",
				"Planoles                       ",
				"Plans de Sió                   ",
				"Poal                           ",
				"Pobla de Cérvoles              ",
				"Pobla de Claramunt             ",
				"Pobla de Lillet                ",
				"Pobla de Mafumet               ",
				"Pobla de Massaluca             ",
				"Pobla de Montornès             ",
				"Pobla de Segur                 ",
				"Poboleda                       ",
				"Polinyà                        ",
				"Pont d'Armentera               ",
				"Pont de Bar                    ",
				"Pont de Molins                 ",
				"Pont de Suert                  ",
				"Pont de Vilomara i Rocafort    ",
				"Pontons                        ",
				"Pontils                        ",
				"Pontós                         ",
				"Ponts                          ",
				"Porqueres                      ",
				"Porrera                        ",
				"Port de la Selva               ",
				"Portbou                        ",
				"Portella                       ",
				"Pradell de la Teixeta          ",
				"Prades                         ",
				"Prat de Comte                  ",
				"Prat de Llobregat              ",
				"Pratdip                        ",
				"Prats de Lluçanès              ",
				"Prats de Rei                   ",
				"Prats i Sansor                 ",
				"Preixana                       ",
				"Preixens                       ",
				"Premià de Dalt                 ",
				"Premià de Mar                  ",
				"Preses                         ",
				"Prullans                       ",
				"Puig-reig                      ",
				"Puigcerdà                      ",
				"Puigdàlber                     ",
				"Puiggròs                       ",
				"Puigpelat                      ",
				"Puigverd d'Agramunt            ",
				"Puigverd de Lleida             ",
				"Pujalt                         ",
				"Quar                           ",
				"Quart                          ",
				"Queralbs                       ",
				"Querol                         ",
				"Rabós                          ",
				"Rajadell                       ",
				"Rasquera                       ",
				"Regencós                       ",
				"Rellinars                      ",
				"Renau                          ",
				"Reus                           ",
				"Rialp                          ",
				"Riba                           ",
				"Riba-roja d'Ebre               ",
				"Ribera d'Ondara                ",
				"Ribera d'Urgellet              ",
				"Ribes de Freser                ",
				"Riells i Viabrea               ",
				"Riera de Gaià                  ",
				"Riner                          ",
				"Ripoll                         ",
				"Ripollet                       ",
				"Riu de Cerdanya                ",
				"Riudarenes                     ",
				"Riudaura                       ",
				"Riudecanyes                    ",
				"Riudecols                      ",
				"Riudellots de la Selva         ",
				"Riudoms                        ",
				"Riumors                        ",
				"Roca del Vallès                ",
				"Rocafort de Queralt            ",
				"Roda de Barà                   ",
				"Roda de Ter                    ",
				"Rodonyà                        ",
				"Roquetes                       ",
				"Roses                          ",
				"Rosselló                       ",
				"Rourell                        ",
				"Rubió                          ",
				"Rubí                           ",
				"Rupit i Pruit                  ",
				"Rupià                          ",
				"Sabadell                       ",
				"Sagàs                          ",
				"Saldes                         ",
				"Sales de Llierca               ",
				"Sallent                        ",
				"Salomó                         ",
				"Salou                          ",
				"Salt                           ",
				"Salàs de Pallars               ",
				"Sanaüja                        ",
				"Sant Adrià de Besòs            ",
				"Sant Agustí de Lluçanès        ",
				"Sant Andreu Salou              ",
				"Sant Andreu de Llavaneres      ",
				"Sant Andreu de la Barca        ",
				"Sant Aniol de Finestres        ",
				"Sant Antoni de Vilamajor       ",
				"Sant Bartomeu del Grau         ",
				"Sant Boi de Llobregat          ",
				"Sant Boi de Lluçanès           ",
				"Sant Carles de la Ràpita       ",
				"Sant Cebrià de Vallalta        ",
				"Sant Celoni                    ",
				"Sant Climent Sescebes          ",
				"Sant Climent de Llobregat      ",
				"Sant Cugat Sesgarrigues        ",
				"Sant Cugat del Vallès          ",
				"Sant Esteve Sesrovires         ",
				"Sant Esteve de Palautordera    ",
				"Sant Esteve de la Sarga        ",
				"Sant Feliu Sasserra            ",
				"Sant Feliu de Buixalleu        ",
				"Sant Feliu de Codines          ",
				"Sant Feliu de Guíxols          ",
				"Sant Feliu de Llobregat        ",
				"Sant Feliu de Pallerols        ",
				"Sant Ferriol                   ",
				"Sant Fost de Campsentelles     ",
				"Sant Fruitós de Bages          ",
				"Sant Gregori                   ",
				"Sant Guim de Freixenet         ",
				"Sant Guim de la Plana          ",
				"Sant Hilari Sacalm             ",
				"Sant Hipòlit de Voltregà       ",
				"Sant Iscle de Vallalta         ",
				"Sant Jaume d'Enveja            ",
				"Sant Jaume de Frontanyà        ",
				"Sant Jaume de Llierca          ",
				"Sant Jaume dels Domenys        ",
				"Sant Joan Despí                ",
				"Sant Joan de Mollet            ",
				"Sant Joan de Vilatorrada       ",
				"Sant Joan de les Abadesses     ",
				"Sant Joan les Fonts            ",
				"Sant Jordi Desvalls            ",
				"Sant Julià de Cerdanyola       ",
				"Sant Julià de Ramis            ",
				"Sant Julià de Vilatorta        ",
				"Sant Julià del Llor i Bonmatí  ",
				"Sant Just Desvern              ",
				"Sant Llorenç Savall            ",
				"Sant Llorenç d'Hortons         ",
				"Sant Llorenç de Morunys        ",
				"Sant Llorenç de la Muga        ",
				"Sant Martí Sarroca             ",
				"Sant Martí Sesgueioles         ",
				"Sant Martí Vell                ",
				"Sant Martí d'Albars            ",
				"Sant Martí de Centelles        ",
				"Sant Martí de Llémena          ",
				"Sant Martí de Riucorb          ",
				"Sant Martí de Tous             ",
				"Sant Mateu de Bages            ",
				"Sant Miquel de Campmajor       ",
				"Sant Miquel de Fluvià          ",
				"Sant Mori                      ",
				"Sant Pau de Segúries           ",
				"Sant Pere Pescador             ",
				"Sant Pere Sallavinera          ",
				"Sant Pere de Ribes             ",
				"Sant Pere de Riudebitlles      ",
				"Sant Pere de Torelló           ",
				"Sant Pere de Vilamajor         ",
				"Sant Pol de Mar                ",
				"Sant Quintí de Mediona         ",
				"Sant Quirze Safaja             ",
				"Sant Quirze de Besora          ",
				"Sant Quirze del Vallès         ",
				"Sant Ramon                     ",
				"Sant Sadurní d'Anoia           ",
				"Sant Sadurní d'Osormort        ",
				"Sant Salvador de Guardiola     ",
				"Sant Vicenç de Castellet       ",
				"Sant Vicenç de Montalt         ",
				"Sant Vicenç de Torelló         ",
				"Sant Vicenç dels Horts         ",
				"Santa Bàrbara                  ",
				"Santa Cecília de Voltregà      ",
				"Santa Coloma de Cervelló       ",
				"Santa Coloma de Farners        ",
				"Santa Coloma de Gramenet       ",
				"Santa Coloma de Queralt        ",
				"Santa Cristina d'Aro           ",
				"Santa Eugènia de Berga         ",
				"Santa Eulàlia de Riuprimer     ",
				"Santa Eulàlia de Ronçana       ",
				"Santa Fe del Penedès           ",
				"Santa Llogaia d'Àlguema        ",
				"Santa Margarida de Montbui     ",
				"Santa Margarida i els Monjos   ",
				"Santa Maria d'Oló              ",
				"Santa Maria de Besora          ",
				"Santa Maria de Corcó           ",
				"Santa Maria de Martorelles     ",
				"Santa Maria de Merlès          ",
				"Santa Maria de Miralles        ",
				"Santa Maria de Palautordera    ",
				"Santa Oliva                    ",
				"Santa Pau                      ",
				"Santa Perpètua de Mogoda       ",
				"Santa Susanna                  ",
				"Santpedor                      ",
				"Sarral                         ",
				"Sarrià de Ter                  ",
				"Sarroca de Bellera             ",
				"Sarroca de Lleida              ",
				"Saus                           ",
				"Savallà del Comtat             ",
				"Secuita                        ",
				"Selva de Mar                   ",
				"Selva del Camp                 ",
				"Senan                          ",
				"Senterada                      ",
				"Sentiu de Sió                  ",
				"Sentmenat                      ",
				"Serinyà                        ",
				"Serra de Daró                  ",
				"Seròs                          ",
				"Setcases                       ",
				"Seu d'Urgell                   ",
				"Seva                           ",
				"Sénia                          ",
				"Sidamon                        ",
				"Sils                           ",
				"Sitges                         ",
				"Siurana                        ",
				"Sobremunt                      ",
				"Soleràs                        ",
				"Solivella                      ",
				"Solsona                        ",
				"Sora                           ",
				"Soriguera                      ",
				"Sort                           ",
				"Soses                          ",
				"Subirats                       ",
				"Sudanell                       ",
				"Sunyer                         ",
				"Susqueda                       ",
				"Súria                          ",
				"Tagamanent                     ",
				"Talamanca                      ",
				"Talarn                         ",
				"Talavera                       ",
				"Tallada d'Empordà              ",
				"Taradell                       ",
				"Tarragona                      ",
				"Tarrés                         ",
				"Tarroja de Segarra             ",
				"Tavertet                       ",
				"Tavèrnoles                     ",
				"Teià                           ",
				"Terrades                       ",
				"Terrassa                       ",
				"Térmens                        ",
				"Tiana                          ",
				"Tiurana                        ",
				"Tivenys                        ",
				"Tivissa                        ",
				"Tírvia                         ",
				"Tona                           ",
				"Tordera                        ",
				"Torelló                        ",
				"Torms                          ",
				"Tornabous                      ",
				"Torre de Cabdella              ",
				"Torre de Claramunt             ",
				"Torre de Fontaubella           ",
				"Torre de l'Espanyol            ",
				"Torre-serona                   ",
				"Torrebesses                    ",
				"Torredembarra                  ",
				"Torrefarrera                   ",
				"Torrefeta i florejacs          ",
				"Torregrossa                    ",
				"Torrelameu                     ",
				"Torrelavit                     ",
				"Torrelles de Foix              ",
				"Torrelles de Llobregat         ",
				"Torrent                        ",
				"Torres de Segre                ",
				"Torroella de Fluvià            ",
				"Torroella de Montgrí           ",
				"Torroja del Priorat            ",
				"Tortellà                       ",
				"Tortosa                        ",
				"Torà                           ",
				"Toses                          ",
				"Tossa de Mar                   ",
				"Tremp                          ",
				"Tàrrega                        ",
				"Ullastrell                     ",
				"Ullastret                      ",
				"Ulldecona                      ",
				"Ulldemolins                    ",
				"Ullà                           ",
				"Ultramort                      ",
				"Urús                           ",
				"Vacarisses                     ",
				"Vajol                          ",
				"Vall d'en Bas                  ",
				"Vall de Boí                    ",
				"Vall de Bianya                 ",
				"Vall de Cardós                 ",
				"Vall-llobrega                  ",
				"Vallbona d'Anoia               ",
				"Vallbona de les Monges         ",
				"Vallcebre                      ",
				"Vallclara                      ",
				"Vallfogona de Balaguer         ",
				"Vallfogona de Ripollès         ",
				"Vallfogona de Riucorb          ",
				"Vallgorguina                   ",
				"Vallirana                      ",
				"Vallmoll                       ",
				"Vallromanes                    ",
				"Valls                          ",
				"Valls d'Aguilar                ",
				"Valls de Valira                ",
				"Vandellòs i l'Hosp.de l'Infant ",
				"Vansa i Fórnols                ",
				"Veciana                        ",
				"Vendrell                       ",
				"Ventalló                       ",
				"Verdú                          ",
				"Verges                         ",
				"Vespella de Gaià               ",
				"Vic                            ",
				"Vidreres                       ",
				"Vidrà                          ",
				"Vielha e Mijaran               ",
				"Vila-rodona                    ",
				"Vila-sacra                     ",
				"Vila-sana                      ",
				"Vila-seca                      ",
				"Vilabella                      ",
				"Vilabertran                    ",
				"Vilablareix                    ",
				"Vilada                         ",
				"Viladamat                      ",
				"Viladasens                     ",
				"Viladecans                     ",
				"Viladecavalls                  ",
				"Vilademuls                     ",
				"Viladrau                       ",
				"Vilafant                       ",
				"Vilafranca del Penedès         ",
				"Vilagrassa                     ",
				"Vilajuïga                      ",
				"Vilalba Sasserra               ",
				"Vilalba dels Arcs              ",
				"Vilaller                       ",
				"Vilallonga de Ter              ",
				"Vilallonga del Camp            ",
				"Vilamacolum                    ",
				"Vilamalla                      ",
				"Vilamaniscle                   ",
				"Vilamòs                        ",
				"Vilanant                       ",
				"Vilanova d'Escornalbou         ",
				"Vilanova de Bellpuig           ",
				"Vilanova de Meià               ",
				"Vilanova de Prades             ",
				"Vilanova de Sau                ",
				"Vilanova de Segrià             ",
				"Vilanova de l'Aguda            ",
				"Vilanova de la Barca           ",
				"Vilanova del Camí              ",
				"Vilanova del Vallès            ",
				"Vilanova i la Geltrú           ",
				"Vilaplana                      ",
				"Vilassar de Dalt               ",
				"Vilassar de Mar                ",
				"Vilaverd                       ",
				"Vilaür                         ",
				"Vilella Alta                   ",
				"Vilella Baixa                  ",
				"Vilobí d'Onyar                 ",
				"Vilobí del Penedès             ",
				"Vilopriu                       ",
				"Vilosell                       ",
				"Vimbodí                        ",
				"Vinaixa                        ",
				"Vinebre                        ",
				"Vinyols i els Arcs             ",
				"Viver i Serrateix              ",
				"Xerta                          "

			});

			/* Buttons */
			buttonSimple = new Button ();
			buttonSimple.Location = new Point (280, 30);
			buttonSimple.Text = "Simple";
			buttonSimple.Size = new Size (100, 23);
			buttonSimple.Click += new System.EventHandler (buttonSimpleClick);

			buttonDropDown = new Button ();
			buttonDropDown.Location = new Point (280, 80);
			buttonDropDown.Text = "DropList";
			buttonDropDown.Size = new Size (100, 23);
			buttonDropDown.Click += new System.EventHandler (buttonDropDownClick);

			buttonDropDownList = new Button ();
			buttonDropDownList.Location = new Point (280, 130);
			buttonDropDownList.Text = "DropDownList";
			buttonDropDownList.Size = new Size (100, 23);
			buttonDropDownList.Click += new System.EventHandler (buttonDropDownListClick);
						
			comboBox.Location = new System.Drawing.Point(8, 32);
			comboBox.Name = "comboBox";
			comboBox.Size = new System.Drawing.Size (248, 150);
			comboBox.TabIndex = 0;
			comboBox.Text = "A normal ComboBox";
			comboBox.DropDownStyle = ComboBoxStyle.Simple;
			comboBox.MaxDropDownItems = 10;
			
			//this.comboBox.IntegralHeight = true;			
			//comboBox.Font = new System.Drawing.Font (comboBox.Font.FontFamily, comboBox.Font.Size + 5);
			
			
			// 
			// MainForm
			// 
			this.ClientSize = new System.Drawing.Size(624, 309);
			this.Controls.AddRange(new Control[] {						
						comboBox, buttonSimple, buttonDropDown, buttonDropDownList});
						
			this.Text = "Single ComboBox sample";
			this.ResumeLayout(false);
			
			Console.WriteLine ("ComboBox Size {0}", comboBox.Size);
			Console.WriteLine ("ComboBox IntegralHeight {0}", comboBox.IntegralHeight);
			Console.WriteLine ("ComboBox ItemHeight {0}", comboBox.ItemHeight);
			Console.WriteLine ("ComboBox FontHeight {0}", comboBox.Font.Height);			
			
		}

		private void buttonSimpleClick (object sender, System.EventArgs e)
		{
			comboBox.DropDownStyle = ComboBoxStyle.Simple;
		}

		private void buttonDropDownClick (object sender, System.EventArgs e)
		{
			comboBox.DropDownStyle = ComboBoxStyle.DropDown;
		}

		private void buttonDropDownListClick (object sender, System.EventArgs e)
		{
			comboBox.DropDownStyle = ComboBoxStyle.DropDownList;
		}
		
		public static void Main (string[] args)
		{
			Application.Run (new MainForm ());
		}
	}			
}
